# Generated by Django 4.1 on 2022-09-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_apps', '0002_post_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='coding', max_length=1000),
        ),
    ]
